CATALOG_FILE_PATH = './../assets/catalog.csv'
SALES_FILE_PATH = './../assets/sales-10K.csv'

KEY_ITEM_ID = 'item_id'
KEY_COUNTRY = 'country'
KEY_CITY = 'city'
KEY_TS = 'ts'
KEY_PRICE = 'price'

CATALOG_COLUMN_ITEM_ID = 0
CATALOG_COLUMN_CATEGORY = 5

SALE_COLUMN_ITEM_ID = 0
SALE_COLUMN_COUNTRY = 1
SALE_COLUMN_CITY = 2
SALE_COLUMN_TS = 3
SALE_COLUMN_PRICE = 4
